language: python
python:
  - "3.7"
  
install:
  - pip install -r requirements.txt

script:
  #- pytest
  - make test
  
git:
  depth: 3
  
notifications:
    email:
        recipients:
            - kasuru@hotmail.com
            - julita_056@hotmail.com
        on_success: always
        on_failure: always

deploy:
    provider: heroku
    skip-cleanup: true
    keep-history: true
    api_key: 0974ee04-82a5-4897-85ee-4a86b3f45be4
    app: mercanotas-backend
    on:
        repo: TonyLuque/mercanotas_backend
